name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true  # 啟用 LFS 拉取歷史大檔案

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Install Git LFS and huggingface_hub
        run: |
          git lfs install
          python -m pip install huggingface_hub

      - name: Clean Working Directory
        run: |
          # 清理未提交變更
          git status
          if [ -n "$(git status --porcelain)" ]; then
            echo "Working directory is dirty, committing changes"
            git add .
            git commit -m "Auto-commit untracked changes before LFS migration" || echo "No changes to commit"
          else
            echo "Working directory is clean"
          fi

      - name: Configure Git LFS
        run: |
          # 更新 .gitattributes
          echo '*.psd filter=lfs diff=lfs merge=lfs -text' > .gitattributes
          echo '*.jpg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.jpeg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.png filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.gif filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.webp filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.svg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.mp4 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.pdf filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.zip filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.woff2 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          # 確保核心文本檔案不使用 LFS
          echo '*.html -filter -diff -merge -text' >> .gitattributes
          echo '*.css -filter -diff -merge -text' >> .gitattributes
          echo '*.js -filter -diff -merge -text' >> .gitattributes
          echo '*.xml -filter -diff -merge -text' >> .gitattributes
          echo '*.json -filter -diff -merge -text' >> .gitattributes
          echo '*.txt -filter -diff -merge -text' >> .gitattributes
          git add .gitattributes
          git commit -m "Configure Git LFS for binary files" || echo "No changes to commit for .gitattributes"

      - name: Migrate Existing Binary Files to LFS
        run: |
          # 遷移歷史中的二進制檔案到 LFS
          git lfs migrate import --include="*.psd,*.jpg,*.jpeg,*.png,*.gif,*.webp,*.svg,*.mp4,*.pdf,*.zip,*.woff2" --everything --verbose --force || echo "Migration skipped or no changes"
          git add .
          git commit -m "Migrate binary files to Git LFS" || echo "No migration changes to commit"

      - name: Push LFS Objects
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 使用 huggingface_hub CLI 認證並推送 LFS 物件
          echo "${HF_TOKEN}" | huggingface-cli login --token
          git lfs push --all hf_space main || echo "No LFS objects to push"

      - name: Add Hugging Face Space Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: hang3976
          SPACE_NAME: test
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set"
            exit 1
          fi
          git remote add hf_space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}" || git remote set-url hf_space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}"
          git remote -v

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy from GitHub Action to Hugging Face Space with Git LFS" || echo "No changes to commit"
          git push --force hf_space main
