name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false  # LibreTV 可能不需要 LFS，根據需要設置

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Check and Switch to Main Branch
        run: |
          if git rev-parse --verify main >/dev/null 2>&1; then
            git checkout main
          else
            git checkout -b main
          fi

      - name: Configure Git LFS (if needed)
        run: |
          git lfs install
          # 僅為大文件設置 LFS（根據需要調整）
          echo '*.jpg filter=lfs diff=lfs merge=lfs -text' > .gitattributes
          echo '*.jpeg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.png filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.gif filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.webp filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.svg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.mp4 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.pdf filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.zip filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.woff2 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          # 確保核心文件不使用 LFS
          echo '*.html -filter -diff -merge -text' >> .gitattributes
          echo '*.css -filter -diff -merge -text' >> .gitattributes
          echo '*.js -filter -diff -merge -text' >> .gitattributes
          echo '*.xml -filter -diff -merge -text' >> .gitattributes
          echo '*.json -filter -diff -merge -text' >> .gitattributes
          echo '*.txt -filter -diff -merge -text' >> .gitattributes
          git add .gitattributes
          git commit -m "Update .gitattributes for LFS" || echo "No changes to commit"

      - name: Add Hugging Face Space Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: hang3976
          SPACE_NAME: test
        run: |
          git remote add hf_space https://hf_token:`\({HF_TOKEN}@huggingface.co/spaces/\)`{HF_USER}/`\({SPACE_NAME} || git remote set-url hf_space https://hf_token:\)`{HF_TOKEN}@huggingface.co/spaces/`\({HF_USER}/\)`{SPACE_NAME}

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy from GitHub Action to Hugging Face Space" || echo "No changes to commit"
          git push --force hf_space main
