name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add Hugging Face Space Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: hang3976
          SPACE_NAME: test
        run: |
          # 檢查 HF_TOKEN 是否存在
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set"
            exit 1
          fi
          # 正確的 URL 格式，使用雙引號允許變數擴展
          git remote add hf_space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}" || git remote set-url hf_space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}"
          # 驗證遠程 URL（不顯示 Token，但確認設置）
          git remote -v

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy from GitHub Action to Hugging Face Space" || echo "No changes to commit"
          git push --force hf_space main
