name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true  # 啟用 LFS 以拉取大檔案

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Install and Configure Git LFS
        run: |
          git lfs install
          # 創建/更新 .gitattributes 以追蹤二進制/大檔案類型
          echo '*.psd filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.jpg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.jpeg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.png filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.gif filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.webp filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.svg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.mp4 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.pdf filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.zip filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.woff2 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          # 確保核心文本檔案不使用 LFS
          echo '*.html -filter -diff -merge -text' >> .gitattributes
          echo '*.css -filter -diff -merge -text' >> .gitattributes
          echo '*.js -filter -diff -merge -text' >> .gitattributes
          echo '*.xml -filter -diff -merge -text' >> .gitattributes
          echo '*.json -filter -diff -merge -text' >> .gitattributes
          echo '*.txt -filter -diff -merge -text' >> .gitattributes
          git add .gitattributes
          git commit -m "Configure Git LFS for binary files" || echo "No changes to commit for .gitattributes"

      - name: Add Hugging Face Space Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: hang3976
          SPACE_NAME: test
        run: |
          # 檢查 HF_TOKEN 是否存在
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set"
            exit 1
          fi
          # 正確的 URL 格式，使用雙引號允許變數擴展
          git remote add hf_space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}" || git remote set-url hf_space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}"
          # 驗證遠程 URL（不顯示 Token）
          git remote -v

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy from GitHub Action to Hugging Face Space with Git LFS" || echo "No changes to commit"
          git push --force hf_space main
